version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ft_transcendence
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  waf:
    image: nginx:1.25
    container_name: waf_service
    ports:
      - "80:80"
    volumes:
      - ./services/waf:/etc/nginx/conf.d
    depends_on:
      - db

volumes:
  postgres_data:
